name: checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  mypy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2

    - name: Install mypy
      run: |
        pip install --upgrade pip
        pip install mypy
        mypy --version

    #- name: Install dependencies
    #  run: pip install ...

    - name: Run mypy
      run: mypy --python-version {{ '${{ matrix.python }}' }} -p {{ cookiecutter.project_name }}


  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Run pre-commit
      uses: pre-commit/action@v2.0.0
